# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-24 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_unit_multiple_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='multiple_record',
            new_name='parallel_records',
        ),
    ]
