# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 10:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20180124_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='duration_of_record',
            field=models.DurationField(default=datetime.timedelta(1), verbose_name='Длительность записи'),
        ),
        migrations.AddField(
            model_name='unit',
            name='end_work',
            field=models.TimeField(default=datetime.time(21, 0), verbose_name='Время окончания работы установки'),
        ),
        migrations.AddField(
            model_name='unit',
            name='start_work',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Время начала работы установки'),
        ),
    ]
